### ISSUE TITLE
Not an issue, I just want to remove RED color from picker

### ISSUE THREAD

**Issue by jigs611989** [justinmeiners/ios-color-wheel#10]
![screen shot 2016-06-20 at 6 52 27 pm](https://cloud.githubusercontent.com/assets/12206811/16195835/0536c968-3719-11e6-80cd-6f2dc4640e4d.png)

I want to implement something like this one, not exactly same but similar color shades.

I have create something like this one using this code. but not look smooth .
![screen shot 2016-06-20 at 7 09 18 pm](https://cloud.githubusercontent.com/assets/12206811/16196244/f0dc98d8-371a-11e6-8384-51b591feda64.png)

Thanks

**Comment by justinmeiners** [comment]
I am not sure how you would do that. The color wheel uses the HSV color space. Perhaps you could clip off the red hues, but im not sure how to go about that.

**Comment by jigs611989** [comment]
Never mind, I have used Image now, And get (R,G,B) at touch point. Here is link : https://github.com/jigs611989/ColorAtPointOnUIImageView.git

Thanks for your reply 👍

**Comment by justinmeiners** [comment]
Glad you got that working. For less conventional color palettes I imagine an image, or a picker from several colors would be best.
