### ISSUE TITLE
Set a color to Color Wheel

### ISSUE THREAD

**Issue by jrosales90** [justinmeiners/ios-color-wheel#12]
I have rgb slider, and I need to update the Color Wheel with a new color, but your class not have method to update color, or has it? Thanks for the class, is amazing.

**Comment by justinmeiners** [comment]
@Jarboox It does the method is:
```
- (void)setCurrentColor:(UIColor*)color
```

**Comment by jrosales90** [comment]
Thanks, I did found it.
