### ISSUE TITLE
Float Architecture Problem

### ISSUE THREAD

**Issue by kpsharp** [justinmeiners/ios-color-wheel#4]
In the function _setCurrentColor:_, the hue, saturation, brightness, and alpha values are initialized as floats, instead of the CGFloats that the _getHue: saturation: brightness: alpha:_ function accepts. This should be changed, as depending on the architecture CGFloats might not be a float (could be a double, for example). This will get the returned values as completely wrong (I was seeing 1.87 and whatnot when I discovered this, which caused the color wheel to look somewhat cool but totally incorrect).

Changing the types to CGFloats fixes this problem.

**Comment by cprovatas** [comment]
setCurrentColor is not working for me in Swift 3 :( Xcode 8.2.  Tried changing floats to CGFloats to no avail.

**Comment by cprovatas** [comment]
scratch that got it work now.  For anyone else who may have this issue,  if you call setCurrentColor in the viewDidLoad, you may need to call layoutIfNeeded() on your colorWheel before or after setting the color.
