### ISSUE TITLE
Set pick point (set the current color)

### ISSUE THREAD

**Issue by pearlpdx** [justinmeiners/ios-color-wheel#8]
Is there an easy way to set the pick point (current color)  
colorWheel.setCurrentColor(UIColor.greenColor())    //I am working is swift
This give me a very artistic color wheel.

**Comment by pearlpdx** [comment]
Fixed with the following change to your code:

- (void)setCurrentColor:(UIColor*)color
{
//    float h = 0.0;
//    float s = 0.0;
//    float b = 1.0;
//    float a = 1.0;
    
    CGFloat h = 0.0;
    CGFloat s = 0.0;
    CGFloat b = 1.0;
    CGFloat a = 1.0;

**Comment by justinmeiners** [comment]
I don't quite understand, the float/CGFloat issue prevented you from using setCurrentColor?

I have not been able to update this project in a while, when I get some time I would love to.

**Comment by pearlpdx** [comment]
Justin

It was just an xCode version issue. It gave me a warning. You should try it with current release it make an exciting color wheel. 

All else is just great. 

Thanks

Gordon Pearlman
Gordon@pearlmanoffice.com
